trailing white spaces are removed
(Logical change 1.4990)

diff --git a/ulevel/shortlived b/ulevel/shortlived
--- a/ulevel/shortlived
+++ b/ulevel/shortlived
@@ -30,13 +30,13 @@ while true ;do
 			limit=$2
 			shift 2
 		;;
-		--) 
-			shift 
-			break 
+		--)
+			shift
+			break
 		;;
-		*) 
-			echo "Internal error!" 
-			exit 1 
+		*)
+			echo "Internal error!"
+			exit 1
 		;;
 	esac
 done
